"""empty message

Revision ID: 3caab8088315
Revises: 
Create Date: 2020-08-04 13:15:27.479902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3caab8088315'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('no_of_cells', sa.Integer(), nullable=True),
    sa.Column('production_date', sa.DateTime(), nullable=True),
    sa.Column('company', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('discharge_rate', sa.Float(), nullable=True),
    sa.Column('maintenance_voltage', sa.Float(), nullable=True),
    sa.Column('full_charge_voltage', sa.Float(), nullable=True),
    sa.Column('min_voltage', sa.Float(), nullable=True),
    sa.Column('no_of_battery_cycles', sa.Integer(), nullable=True),
    sa.Column('first_usage_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battery_id', sa.Integer(), nullable=True),
    sa.Column('chargering_station_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('charge_tape', sa.Enum('charging', 'discharging', 'maintenance', name='chargestateenum'), nullable=True),
    sa.Column('start_voltage', sa.Float(), nullable=True),
    sa.Column('end_voltage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['battery_id'], ['battery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charge_measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=True),
    sa.Column('timestep', sa.DateTime(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('amps', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charge_id'], ['charge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charge_measurement')
    op.drop_table('charge')
    op.drop_table('battery')
    # ### end Alembic commands ###
