"""empty message

Revision ID: 59e2e340aa4c
Revises: d47c9b197118
Create Date: 2020-08-11 06:49:50.267885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e2e340aa4c'
down_revision = 'd47c9b197118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('charge_battery_id_fkey', 'charge', type_='foreignkey')
    op.create_foreign_key(None, 'charge', 'battery', ['battery_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'charge', type_='foreignkey')
    op.create_foreign_key('charge_battery_id_fkey', 'charge', 'battery', ['battery_id'], ['id'])
    # ### end Alembic commands ###
