"""empty message

Revision ID: 733e07376a9e
Revises: d47c9b197118
Create Date: 2020-08-12 10:21:03.145666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733e07376a9e'
down_revision = 'd47c9b197118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('charge_battery_id_fkey', 'charge', type_='foreignkey')
    op.create_foreign_key(None, 'charge', 'battery', ['battery_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('charge_measurement_charge_id_fkey', 'charge_measurement', type_='foreignkey')
    op.create_foreign_key(None, 'charge_measurement', 'charge', ['charge_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'charge_measurement', type_='foreignkey')
    op.create_foreign_key('charge_measurement_charge_id_fkey', 'charge_measurement', 'charge', ['charge_id'], ['id'])
    op.drop_constraint(None, 'charge', type_='foreignkey')
    op.create_foreign_key('charge_battery_id_fkey', 'charge', 'battery', ['battery_id'], ['id'])
    # ### end Alembic commands ###
